common: &common
  timeout_in_minutes: 60
  retry:
    automatic:
        # These are designed to trap and retry failures because agent lost connection.
        # Agent exits with -1 in this case.
      - exit_status: -1
        limit: 3
      - exit_status: 255
        limit: 3
      - exit_status: 128
        limit: 3

linux_agent: &linux_agent
  agents:
    - "agent_count=1"
    - "capable_of_building=worker-sdk"
    - "environment=production"
    - "permission_set=builder"
    - "platform=linux"
    - "scaler_version=2"
    - "machine_type=half"
    - "queue=${CI_LINUX_BUILDER_QUEUE:-v4-20-02-18-132251-bk8410-2dfa8e1336170745}"
  <<: *common

macos_agent: &macos_agent
  agents:
    - "queue=${CI_MACOS_BUILDER_QUEUE:-macos_worker-sdk_17b57b101ca8ff76}"
    - "environment=production"
  <<: *common

windows_agent: &windows_agent
  agents:
    - "agent_count=1"
    - "capable_of_building=worker-sdk"
    - "environment=production"
    - "machine_type=half"
    - "permission_set=builder"
    - "platform=windows"
    - "scaler_version=2"
    - "queue=${CI_WINDOWS_BUILDER_QUEUE:-v4-20-03-23-115927-bk9815-bce0c4a4}"
  <<: *common

steps:
  - label: "build-linux"
    command: "ci/build.sh"
    <<: *linux_agent
  - label: "build-macos"
    command: "ci/build.sh"
    <<: *macos_agent
  - label: "build-windows"
    command: "bash -c ci/build.sh"
    <<: *windows_agent

  - wait:

  - label: build-steps-passed
    command: echo Build steps passed!
    <<: *linux_agent
